### ISSUE TITLE
Numerical labels for detector elements are not consistent with the text label

### ISSUE THREAD

**Issue by mattbellis** [cms-opendata-workshop/workshop2023-lesson-cms-detector#1]
The interactive detector view is amazing!

There is a minor issues with the pop-up labels. If I mouse-over the number on the detector, for example "2" for the ECAL, the pop-up label always says "1".

**Comment by tpmccauley** [comment]
This is what I see

![Screenshot from 2023-06-11 20-16-22](https://github.com/cms-opendata-workshop/workshop2023-lesson-cms-detector/assets/496503/118db3f3-7ef5-4775-99eb-0994d8baa4ca)
![Screenshot from 2023-06-11 20-16-10](https://github.com/cms-opendata-workshop/workshop2023-lesson-cms-detector/assets/496503/195a40cc-0a08-491d-bd2d-2cb98edee6d3)

**Comment by tpmccauley** [comment]
Does this behavior persist when you zoom in/out or rotate?

**Comment by mattbellis** [comment]
This is what I see. And yeah, it persists when I zoom or rotate. This is with Chrome 112 on a Linux machine. 

![PXL_20230612_152510006](https://github.com/cms-opendata-workshop/workshop2023-lesson-cms-detector/assets/293685/75a0735c-12a2-4e33-b7fe-0004a025f27c)

**Comment by tpmccauley** [comment]
I see this on Linux/Chrome as well. Investigating.

**Comment by tpmccauley** [comment]
It turns out this was a css thing. Fixed via: https://gitlab.cern.ch/cms-comms/3d-assets/detector/-/issues/5
